-- Execute este script no SQL Editor do Supabase

create table if not exists public.avaliacoes (
  id bigint generated by default as identity primary key,
  nome text not null,
  nota integer not null check (nota between 1 and 5),
  comentario text not null,
  foto_url text default '',
  video_url text default '',
  criado_em_ms bigint not null,
  criado_em timestamptz not null default now()
);

alter table public.avaliacoes enable row level security;

-- Remove policies antigas para evitar conflito
DROP POLICY IF EXISTS "avaliacoes_select_public" ON public.avaliacoes;
DROP POLICY IF EXISTS "avaliacoes_insert_public" ON public.avaliacoes;

create policy "avaliacoes_select_public"
on public.avaliacoes
for select
to anon
using (true);

create policy "avaliacoes_insert_public"
on public.avaliacoes
for insert
to anon
with check (
  length(nome) between 2 and 80
  and nota between 1 and 5
  and length(comentario) between 4 and 800
  and coalesce(length(foto_url), 0) <= 2000
  and coalesce(length(video_url), 0) <= 2000
);

-- Bucket para fotos e videos
insert into storage.buckets (id, name, public)
values ('avaliacoes-midia', 'avaliacoes-midia', true)
on conflict (id) do nothing;

-- Policies do Storage
DROP POLICY IF EXISTS "storage_public_read_avaliacoes_midia" ON storage.objects;
DROP POLICY IF EXISTS "storage_public_insert_avaliacoes_midia" ON storage.objects;

create policy "storage_public_read_avaliacoes_midia"
on storage.objects
for select
to anon
using (bucket_id = 'avaliacoes-midia');

create policy "storage_public_insert_avaliacoes_midia"
on storage.objects
for insert
to anon
with check (
  bucket_id = 'avaliacoes-midia'
  and (
    (name like 'fotos/%' and lower(storage.extension(name)) in ('jpg', 'jpeg', 'png', 'webp'))
    or (name like 'videos/%' and lower(storage.extension(name)) in ('mp4', 'mov', 'webm'))
  )
);
